CREATE TABLE `remote_tracks` (
    `id` BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `artist_en` VARCHAR(255) NOT NULL,
    `artist_fa` VARCHAR(255) NOT NULL,
    `title_en` VARCHAR(255) NOT NULL,
    `title_fa` VARCHAR(255) NOT NULL,
    `album_en` VARCHAR(255),
    `album_fa` VARCHAR(255),
    `cover_photo` VARCHAR(1000) NOT NULL,
    `low_quality` VARCHAR(1000),
    `normal_quality` VARCHAR(1000),
    `high_quality` VARCHAR(1000),
    `master_quality` VARCHAR(1000),
    `lyrics` TEXT,
    `genre` VARCHAR(255),
    `lyricist_en` VARCHAR(255),
    `lyricist_fa` VARCHAR(255),
    `composer_en` VARCHAR(255),
    `composer_fa` VARCHAR(255),
    `arranger_en` VARCHAR(255),
    `arranger_fa` VARCHAR(255),
    `mixer_en` VARCHAR(255),
    `mixer_fa` VARCHAR(255),
    `publisher_en` VARCHAR(255),
    `publisher_fa` VARCHAR(255),
    `released_at` DATETIME NOT NULL,
    `url` TEXT NOT NULL,
    INDEX `artist_en_title_en_index` (`artist_en`, `title_en`),
    INDEX `artist_fa_title_fa_index` (`artist_fa`, `title_fa`)
) COLLATE='utf8mb4_unicode_ci';